### ISSUE TITLE
Invalid character in entity name

### ISSUE THREAD

**Issue by seanmcilvenna** [nashwaan/xml-js#75]
I am getting an error when parsing a valid XML document:

```
Error: Invalid character in entity name
Line: 2
Column: 10124
Char:  
    at error (C:\Users\sean.mcilvenna\Code\FHIR.js\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Users\sean.mcilvenna\Code\FHIR.js\node_modules\sax\lib\sax.js:677:7)
    at SAXParser.write (C:\Users\sean.mcilvenna\Code\FHIR.js\node_modules\sax\lib\sax.js:1491:13)
    at Object.module.exports [as xml2js] (C:\Users\sean.mcilvenna\Code\FHIR.js\node_modules\xml-js\lib\xml2js.js:337:12)
```

The problem appears to be coming from the &amp; in the following XML snippet:

```
      <mapping>
        <identity value="rim"/>
        <map value="status Amended &amp; Final are differentiated by whether it is the subject of a ControlAct event with a type of &quot;revise&quot;"/>
      </mapping>
```

However, this snippet *is* valid XML... Can you confirm that this is indeed a bug?

**Comment by baltuonis** [comment]
Same thing
I wanted to write it donw
```
xml = '<a wh="as&d@{*as">what</a>'
var result1 = convert.xml2json(
  xml, {
    compact: true, 
    spaces: 4,
    ignoreAttributes: true,
    attributeValueFn: (attrValue) => entities.encodeXML(attrValue)
  });
```

**Comment by LukasBombach** [comment]
I have the same problem when parsing a Vue Component:

```vue
<template><hr v-if="config && config.var === 'val'" /></template>
```

**Comment by JonasJonny** [comment]
Hi @nashwaan, any comment on this, or #80?
It looks like if XML includes `&` then `xml-js` is searching for `;` and is testing everything between.

Problem is https://github.com/isaacs/sax-js
```
if (isNaN(num) || numStr.toLowerCase() !== entity) {
   strictFail(parser, 'Invalid character entity')
   return '&' + parser.entity + ';'
}
```

or better `true` strict mode in xml2js.js
_(strict - Boolean. Whether or not to be a jerk. Default: false.)_
```
var parser = pureJsParser ? sax.parser(true, {}) : parser = new expat.Parser('UTF-8');

Result:
/node_modules/sax/lib/sax.js:968
      throw this.error
      ^

Error: Invalid character entity
```
=>
```
var parser = pureJsParser ? sax.parser(false, {}) : parser = new expat.Parser('UTF-8');

Result:
OK!
```

I think there should be an option to enable/disable this "strict mode".

**Comment by JonasJonny** [comment]
@nashwaan We really need to have an option how to change `true` to `false`.

**Comment by cthorner** [comment]
anyone working on this?

**Comment by seanmcilvenna** [comment]
I would like to know the same :)

**Comment by damianof** [comment]
Was this ever solved?

**Comment by seanmcilvenna** [comment]
Not to my knowledge.

**Comment by JonasJonny** [comment]
CC: @nashwaan

**Comment by macCesar** [comment]
Alternatives, please!!!

**Comment by prb407** [comment]
Was this ever solved?

**Comment by elron** [comment]
https://stackoverflow.com/questions/24877085/invalid-character-entity-parsing-xml

I used this answer and it worked
